ANCAdmin/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminPanel.urls')),
    url(r'^post/', include(('adminPost.urls', 'adminPost'), namespace='adminPost')),
    url(r'^account/', include(('adminAccount.urls', 'adminAccount'), namespace='adminAccount')),
    url(r'^api/v1/details/doctor/', include(('restDoctor.urls', 'restDoctor'), namespace='restDoctor')),
    url(r'api/v1/account/', include(('restaccount.urls','restaccount'),namespace='restaccount')),

]

adminAccount/urls.py
from django.urls import path

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^login/$', auth_views.LoginView.as_view(template_name='adminAccount/login.html'), name='login'),
	# url(r'^register/$', views.register, name='register'),
]

adminPanel/urls.py
from django.urls import path

from .views import HomePageView, patientListView, errorView

urlpatterns = [
    path('',HomePageView.as_view(), name='admin-home'),
    path('patients/', patientListView.as_view(),name='patient-list'),
    path('error/',errorView.as_view(),name="error")
]

adminPost/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^addDoctor', views.docAdd, name='addDoctor'),
	url(r'^doctorList', views.docList, name='doctorList'),
	url(r'^updateDoctor/(?P<pk>\d+)/$', views.update_doc, name='updateDoctor'),
	url(r'^deleteDoctor/(?P<pk>\d+)/$', views.delete_doc, name='deleteDoctor'),
]

restDoctor/urls.py
from restDoctor import views
from django.conf.urls import url

urlpatterns = [
	url(r'^list/$', views.ListDoctorAPIView.as_view(), name='restdoctor-list'),
	url(r'^add/$', views.AddDoctorAPI.as_view(), name='restdoctor-add'),
    url(r'^delete/(?P<id>[\w-]+)/$', views.DeleteDoctorAPI.as_view(), name='restdoctor-delete'),
    url(r'^edit/(?P<id>[\w-]+)/$', views.UpdateDoctorAPI.as_view(), name='restdoctor-edit'),
]

restaccount/urls.py
from restaccount import views
from django.conf.urls import url
from django.urls import path
from rest_framework.authtoken import views as authviews

urlpatterns = [
	url(r'^register/$', views.Register.as_view(), name='register'),
	path('api-token-auth/', authviews.obtain_auth_token, name='api-token-auth'),
]

adminAccount/models.py
from django.db import models

# Create your models here.

adminPost/models.py
from django.db import models

# Create your models here.

class DoctorPost(models.Model):
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    firstname = models.CharField(max_length=400, default=0)
    lastname = models.CharField(max_length=400, default=0)
    email = models.CharField(max_length=400, default=0)
    mobile = models.IntegerField(default=0)
    def __str__(self):
        return self.firstname

restDoctor/models.py
from django.db import models

# Create your models here.

restaccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class DriverUser(AbstractUser):
	name = models.CharField(max_length=250, default='Name')
	def __str__(self):
		return self.username

adminPost/forms.py
from django import forms
from adminPost.models import DoctorPost


class AddDoctorForm(forms.ModelForm):
    class Meta:
        model = DoctorPost
        exclude = ('author', )


class DoctorList(forms.ModelForm):
    class Meta:
        model = DoctorPost
        exclude = [""]


class UpdateDoctorForm(forms.ModelForm):
    class Meta:
        model = DoctorPost
        exclude = ('author',)

adminAccount/views.py
from django.shortcuts import render

# Create your views here.

adminPanel/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "adminPanel/home.html"

class patientListView(TemplateView):
    template_name = "adminPanel/patient_list.html"

class errorView(TemplateView):
    template_name = "adminPanel/404.html"

adminPost/views.py
from django.shortcuts import render,redirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from adminPost.forms import UpdateDoctorForm

from django.core.paginator import Paginator

# Create your views here.
from adminPost.forms import AddDoctorForm

from adminPost.forms import DoctorList

from adminPost.models import DoctorPost


def docAdd(request):
    form = AddDoctorForm(request.POST)
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            post_saved = form.save(commit=False)
            post_saved.author = request.user.id
            form.save()
    return render(request, 'doctor_form.html', {'form': form })


def docList(request):
    form = DoctorList(request.POST)
    posts = DoctorPost.objects.all().order_by('-id').reverse()
    if request.method == 'POST':
        posts = DoctorPost.objects.filter.order_by('-id').reverse()

    paginator = Paginator(posts,10)
    page = request.GET.get('page')

    posts = paginator.get_page(page)
    context_posts = {
        'posts':posts
    }
    return render(request,'all_doctors.html',context_posts)

def update_doc(request, pk):
    post = DoctorPost.objects.get(pk=pk)
    form = UpdateDoctorForm(request.POST,instance=post)

    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            form.save()
    # if request.is_ajax():
    #     template = 'doctor_update.html'
    # else:
    #     template= 'all_doctors.html'
    return render(request, 'doctor_update.html', {'form': form, 'post': post})

def delete_doc(request, pk):
	post = get_object_or_404(DoctorPost,pk=pk)
	if request.method == 'POST':
		post.delete()
		return redirect('adminPost:doctorList')
	context = {
		"object": post
	}
	return render(request, 'delete.html', context)

restDoctor/views.py
from django.shortcuts import render

from rest_framework.views import APIView

from rest_framework.generics import (
	RetrieveUpdateAPIView,
	DestroyAPIView,
	ListAPIView
	)

from rest_framework.generics import (CreateAPIView, RetrieveUpdateAPIView, DestroyAPIView, ListAPIView, RetrieveAPIView)
from rest_framework.response import Response
from django.http import JsonResponse

from .serializers import listDoctorSerializer
from .serializers import addDoctorSerializer
from .serializers import deleteDoctorSerializer
from .serializers import updateDoctorSerializer

from rest_framework.response import Response

from adminPost.models import DoctorPost

from rest_framework.permissions import (
	IsAuthenticated,
	IsAuthenticatedOrReadOnly,
	)

from .permissions import IsOwnerOrReadOnly



from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication



class ListDoctorAPIView(ListAPIView):
	serializer_class = listDoctorSerializer
	queryset = DoctorPost.objects.all()


class AddDoctorAPI(CreateAPIView):
	# authentication_classes = (TokenAuthentication, SessionAuthentication)
	# permission_classes = (IsAuthenticated,)
	serializer_class = addDoctorSerializer
	queryset = DoctorPost.objects.all()

	def perform_create(self, serializer):
		serializer.save()
		# serializer.save(author = self.request.user.id)

class DeleteDoctorAPI(DestroyAPIView):
	queryset = DoctorPost.objects.all()
	serializer_class = deleteDoctorSerializer
	lookup_field = 'id'
	# permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
	# authentication_classes = (TokenAuthentication, SessionAuthentication)

class UpdateDoctorAPI(RetrieveUpdateAPIView):
	queryset = DoctorPost.objects.all()
	serializer_class = updateDoctorSerializer
	lookup_field = 'id'
	# permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
	# authentication_classes = (TokenAuthentication, SessionAuthentication)

restaccount/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from django.http import HttpResponse
from django.http import JsonResponse

from .serializers import RegisterSerializer

from rest_framework.generics import (CreateAPIView, RetrieveUpdateAPIView, UpdateAPIView, DestroyAPIView, ListAPIView, RetrieveAPIView)
from rest_framework.response import Response

from restaccount.models import DriverUser




from rest_framework.authentication import TokenAuthentication
from rest_framework.authentication import SessionAuthentication


from rest_framework.permissions import IsAuthenticated
from rest_framework.permissions import (
	AllowAny,
	)

class Register(CreateAPIView):
	permission_classes = (AllowAny,)

	serializer_class = RegisterSerializer
	queryset = DriverUser.objects.all()

adminAccount/templates/adminAccount/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from thememinister.com/health/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 12 Sep 2019 20:10:56 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>ANC</title>

    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{% static 'assets/dist/img/ico/favicon.png' %}" type="image/x-icon">


    <!-- Bootstrap -->
    <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Bootstrap rtl -->
    <!--<link href="assets/bootstrap-rtl/bootstrap-rtl.min.css" rel="stylesheet" type="text/css"/>-->
    <!-- Pe-icon-7-stroke -->
    <link href="{% static 'assets/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" rel="stylesheet" type="text/css"/>
    <!-- style css -->
    <link href="{% static 'assets/dist/css/stylehealth.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Theme style rtl -->
    <!--<link href="assets/dist/css/stylehealth-rtl.css" rel="stylesheet" type="text/css"/>-->
</head>
<body>
    <!-- Content Wrapper -->
    <div class="login-wrapper">
<!--        <div class="back-link">-->
<!--            <a href="index-2.html" class="btn btn-success">Back to Dashboard</a>-->
<!--        </div>-->
        <div class="container-center">
            <div class="panel panel-bd">
                <div class="panel-heading">
                    <div class="view-header">
                        <div class="header-icon">
                            <i class="pe-7s-unlock"></i>
                        </div>
                        <div class="header-title">
                            <h3>Login</h3>
                            <small><strong>Please enter your credentials to login.</strong></small>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <form action="" method="post" id="loginForm" novalidate>
                        <div class="form-group">
                            <label class="control-label" for="username">Username</label>
                            <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value="" name="username" id="username" class="form-control">
                            <span class="help-block small">Your unique username to app</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="password">Password</label>
                            <input type="password" title="Please enter your password" placeholder="******" required="" value="" name="password" id="password" class="form-control">
                            <span class="help-block small">Your strong password</span>
                        </div>
                        <div>
                            <button class="btn btn-primary">Login</button>
                            <a class="btn btn-warning" href="register.html">Register</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /.content-wrapper -->
    <!-- jQuery -->
    <script src="assets/plugins/jQuery/jquery-1.12.4.min.js" type="text/javascript"></script>
    <!-- bootstrap js -->
    <script src="assets/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
</body>

<!-- Mirrored from thememinister.com/health/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 12 Sep 2019 20:10:56 GMT -->
</html>

adminPanel/templates/adminPanel/505.html
{% extends "adminPanel/error_base.html" %}
{% block content %}
<div class="middle-box2 text-center">
    <div class="row">
        <div class="col-sm-12">
            <div class="error-text2"><h1>505</h1></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="error-desc2">
                <p>The server encountered something unexpected that didn't allow it to complete the request.
                    We apologize. You can go back to main page:
                </p>
                    <a href="index-2.html" class="btn btn-success">Dashboard</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

adminPanel/templates/adminPanel/error_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>ANC Admin panel</title>

    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{% static 'assets/dist/img/ico/mini-logo.png' %}" type="image/x-icon">

    <!-- Bootstrap -->
    <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Bootstrap rtl -->
    <!--<link href="assets/bootstrap-rtl/bootstrap-rtl.min.css" rel="stylesheet" type="text/css"/>-->
    <!-- Theme style -->
    <link href="{% static 'assets/dist/css/stylehealth.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- Theme style rtl -->
    <!--<link href="assets/dist/css/stylehealth-rtl.css" rel="stylesheet" type="text/css"/>-->
</head>
<body>
{% block content %} {% endblock content %}

<!-- jQuery -->
<script src="{% static 'assets/plugins/jQuery/jquery-1.12.4.min.js' %}" type="text/javascript"></script>
<!-- bootstrap js-->
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

adminPost/templates/all_doctors.html
<!--{% extends "adminPanel/base.html" %}-->
{% load static %}
{% block content %}
<section class="content-header">
                        <div class="header-icon">
                            <i class="pe-7s-box1"></i>
                        </div>
                        <div class="header-title">
                            <form action="#" method="get" class="sidebar-form search-box pull-right hidden-md hidden-lg hidden-sm">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input type="text" name="q" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button type="submit" name="search" id="search-btn" class="btn"><i class="fa fa-search"></i></button>
                                    </span>
                                </div>
                            </form>
                            <h1>Doctor</h1>
                            <small>Doctor list</small>
                            <ol class="breadcrumb hidden-xs">
                                <li><a href="{% url 'admin-home' %}"><i class="pe-7s-home"></i> Home</a></li>
                                <li class="active">Dashboard</li>
                            </ol>
                        </div>
                    </section>
                    <!-- Main content -->
                    <section class="content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-bd lobidrag">
                                    <div class="panel-heading">
                                        <div class="btn-group">
                                            <a class="btn btn-success" href="{% url 'adminPost:addDoctor' %}"> <i class="fa fa-plus"></i> Add Doctor
                                            </a>
                                        </div>
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="panel-header">
                                                <div class="col-sm-4 col-xs-12">
                                                    <div class="dataTables_length">
                                                        <label>Display
                                                            <select name="example_length">
                                                                <option value="10">10</option>
                                                                <option value="25">25</option>
                                                                <option value="50">50</option>
                                                                <option value="100">100</option>
                                                            </select> records per page</label>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-4 col-xs-12">
                                                        <div class="dataTables_length">
                                                         <a class="btn btn-default buttons-copy btn-sm" tabindex="0">
                                                             <span>Copy</span></a>
                                                             <a class="btn btn-default buttons-csv buttons-html5 btn-sm" tabindex="0"><span>CSV</span></a>
                                                             <a class="btn btn-default buttons-excel buttons-html5 btn-sm" tabindex="0"><span>Excel</span></a>
                                                             <a class="btn btn-default buttons-pdf buttons-html5 btn-sm" tabindex="0"><span>PDF</span></a>
                                                             <a class="btn btn-default buttons-print btn-sm" tabindex="0"><span>Print</span></a>

                                                         </div>
                                                     </div>
                                                     <div class="col-sm-4 col-xs-12">
                                                        <div class="dataTables_length">
                                                            <div class="input-group custom-search-form">
                                                                <input type="search" class="form-control" placeholder="search..">
                                                                <span class="input-group-btn">
                                                                  <button class="btn btn-primary" type="button">
                                                                      <span class="glyphicon glyphicon-search"></span>
                                                                  </button>
                                                              </span>
                                                          </div><!-- /input-group -->
                                                      </div>
                                                  </div>
                                              </div>

                                          </div>
                                          <div class="table-responsive">
                                            <table class="table table-bordered table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>First Name</th>
                                                        <th>last Name</th>
                                                        <th>Department</th>
                                                        <th>Email</th>
                                                        <th>Mobile No</th>
                                                        <th>Phone </th>
                                                        <th>Price </th>
                                                        <th>Update</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                {% for post in posts %}

                                                <tr >
<!--                                                     <td>-->
<!--                                                         <input type="radio" name="radioGroup">-->
<!--                                                         <label>{{ post.id }}</label>-->
<!--                                                     </td>-->
<!--                                                     <td><img src="{% static 'assets/dist/img/d3.png' %}" class="img-circle" alt="User Image" height="50" width="50"></td>-->
                                                     <td>
                                                         <input type="radio" name="radioGroup">
                                                         {{ post.firstname }}

                                                     </td>
                                                     <td>{{ post.lastname }}</td>
                                                     <td>Neurology</td>
                                                     <td><a href="#" class="__cf_email__" data-cfemail="f39e8681879289b3879b969e969e9a9d9a80879681dd909c9e">{{ post.email }}</a></td>
                                                     <td>{{ post.mobile }}</td>
                                                     <td>{{ post.mobile }}</td>
                                                     <td>$43</td>
                                                     <td>
                                                         <a href="{% url 'adminPost:updateDoctor' post.id %}" data-toggle="modal" class="btn btn-info btn-xs" data-target="#ordine">
                                                             <i class="fa fa-pencil"></i>
                                                         </a>
                                                         <a href="{% url 'adminPost:deleteDoctor' post.id %}" class="btn btn-danger btn-xs" data-target="#ordine">
                                                             <i class="fa fa-trash-o"></i>
                                                         </a>
<!--                                                        <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#ordine"><i class="fa fa-pencil"></i>-->
<!--                                                             <a href="{% url 'adminPost:updateDoctor' post.id %}"></a>-->
<!--                                                        </button>-->
<!--                                                        <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#ordine"><i class="fa fa-trash-o"></i>-->
<!--                                                        </button>-->
                                                    </td>
                                                </tr>
                                                </tbody>

                                                {% endfor %}
                                             </table>
                                            </div>

                    <div class="page-nation text-right">
                        <ul class="pagination pagination-large">
                            <li class="disabled"><span>«</span></li>
                            <li class="active"><span>1</span></li>
                            <li><a href="#">2</a></li>
                            <li class="disabled"><span>...</span></li><li>
                            <li><a rel="next" href="#">Next</a></li>
                        </ul>
                    </div>

                </div>
            </div>

        </div>

    </div>
</section> <!-- /.content -->

{% include "doctor_update.html" %}

{% endblock %}

adminPost/templates/delete.html
<!-- Modal Dialog -->
<html>


<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Delete Permanently</h4>
      </div>
      <div class="modal-body">

          <form action='.' method='POST'>{% csrf_token %}
             <p>Are you sure you want to delete Dr.{{object.firstname}}'s details?</p>
              <p><input type='submit' value='Yes' />  <a href='../'>Cancel</a></p>
          </form>


      </div>
      <div class="modal-footer">
<!--          <p> <input type='submit' value='Yes' />-->
<!--              <a class="btn btn-default" href='../'>Cancel</a>-->

<!--          </p>-->
<!--        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>-->
<!--        <button type="submit" class="btn btn-danger" id="confirm">Delete</button>-->
      </div>
    </div>
  </div>
</div>

<!-- Dialog show event handler -->
<script type="text/javascript">
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);
      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);

      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });

  <!-- Form confirm (yes/ok) handler, submits form -->
  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });
</script>

</html>